[package]
name = "hello_dynamic"
version = "0.1.0"
authors = ["d0naim"]

[dependencies]
sharer          = { path = "../sharer" }
# libloading      = "0.5.0"
libloading      = { git = "https://github.com/Donaim/rust_libloading" } # added 'into_type' method for Symbol
dynamic         = "0.2.1"